global:
  scrape_interval: 15s
scrape_configs:
- job_name: fastapi_services
  static_configs:
  - targets:
    - host.docker.internal:8000
    - host.docker.internal:8001
    - host.docker.internal:8002
- job_name: mlflow_training
  static_configs:
  - targets:
    - host.docker.internal:8003
  scrape_interval: 30s
- job_name: mlflow_server
  static_configs:
  - targets:
    - host.docker.internal:5000
  metrics_path: /metrics
  scrape_interval: 60s
